// GENERATED FILE — DO NOT EDIT.
// Source: user-app-client/src/lib/errors.ts (hexContractErrors).
// Regenerate via docs/integrations/scripts/generate-revert-selectors.ts (run on 2026-05-21).
//
// Selector count: 130

package xyz.justzappit.offramp.orchestrator

import xyz.justzappit.evm.abi.Selector4

/**
 * Wholesale port of the p2p.me Diamond's custom-error selector table. Every selector
 * the contract emits is mapped to its canonical SDK error name (the same string the
 * official `@p2pdotme/user-app-client` displays via i18n keys). Keeps us byte-aligned
 * with the SDK; do not edit by hand. See script header for regeneration.
 */
object KnownContractErrors {
    private val SELECTOR_TO_NAME: Map<Selector4, String> = mapOf(
        Selector4.fromHex("0x02a6fdd2") to "CURRENCY_NOT_SUPPORTED",
        Selector4.fromHex("0x03683687") to "ORDER_ALREADY_MARKED_COMPLETED",
        Selector4.fromHex("0x0464115c") to "ZK_PASSPORT_AGE_BELOW_MINIMUM",
        Selector4.fromHex("0x0569ab3e") to "DUPLICATE_PAYMENT_CHANNEL",
        Selector4.fromHex("0x071ea33c") to "USER_HAS_NO_REPUTATION",
        Selector4.fromHex("0x07a2454f") to "DISPUTE_CAN_ONLY_BE_RAISED_AFTER_T_MINUTES_OF_ORDER_PLACEMEN",
        Selector4.fromHex("0x0b7c70f3") to "NO_PENDING_UNSTAKE_REQUEST",
        Selector4.fromHex("0x0ece93a6") to "RECOMMENDATION_ALREADY_CLAIMED",
        Selector4.fromHex("0x0ee0b659") to "MERCHANT_NOT_BLACKLISTED",
        Selector4.fromHex("0x0f165e7b") to "NULLIFIER_ALREADY_VERIFIED",
        Selector4.fromHex("0x149f9fca") to "USDC_TRANSFER_FAILED",
        Selector4.fromHex("0x16c726b1") to "NOT_SUPER_ADMIN",
        Selector4.fromHex("0x1775c43e") to "ORDER_NOT_ASSIGNED",
        Selector4.fromHex("0x181b1b2e") to "ORDER_WITH_PLACED_STATUS_ONLY_CAN_BE_REASSIGNED",
        Selector4.fromHex("0x1b19ad97") to "MERCHANT_MONTHLY_REFERRAL_LIMIT_REACHED",
        Selector4.fromHex("0x1b1d7861") to "NO_WITHDRAWABLE_AMOUNT",
        Selector4.fromHex("0x1e3b9629") to "ONLY_PAID_BUY_ORDERS_CAN_BE_MARKED_COMPLETE",
        Selector4.fromHex("0x1fa24b35") to "ZK_PASSPORT_PROOF_INVALID",
        Selector4.fromHex("0x22a5e34b") to "MANAGER_NOT_FOUND",
        Selector4.fromHex("0x2366073b") to "INVALID_SOCIAL_PLATFORM",
        Selector4.fromHex("0x279bbc0c") to "USDC_TRANSFER_FAILED_WITH_PANIC",
        Selector4.fromHex("0x2a829f07") to "INVALID_ORDER_STATUS_TO_RAISE_DISPUTE",
        Selector4.fromHex("0x2c5211c6") to "INVALID_AMOUNT",
        Selector4.fromHex("0x2e757a60") to "INCORRECT_ORDER_TYPE",
        Selector4.fromHex("0x2f850b6b") to "SOCIAL_ALREADY_VERIFIED",
        Selector4.fromHex("0x2f950361") to "UNCLAIMED_REWARDS_EXIST",
        Selector4.fromHex("0x2fdec18b") to "SIGNATURE_VALIDATION_FAILED",
        Selector4.fromHex("0x302c5138") to "CANNOT_CLAIM_REVENUE_FOR_CURRENT_MONTH",
        Selector4.fromHex("0x355b0709") to "FACEBOOK_ONLY_RP_UPDATES",
        Selector4.fromHex("0x36bdb7b6") to "ZK_PASSPORT_IDENTIFIER_ALREADY_VERIFIED",
        Selector4.fromHex("0x3764a75c") to "CANNOT_RAISE_DISPUTE_TWICE",
        Selector4.fromHex("0x3c0ca622") to "NO_REPUTATION",
        Selector4.fromHex("0x3eb17c88") to "INVALID_BLOCK_AMOUNT",
        Selector4.fromHex("0x3eedee0f") to "INVALID_CAMPAIGN_ID",
        Selector4.fromHex("0x3fb087f4") to "NO_REWARDS",
        Selector4.fromHex("0x3fd2347e") to "STAKE_AMOUNT_TOO_LOW",
        Selector4.fromHex("0x403e7fa6") to "FUNCTION_NOT_FOUND",
        Selector4.fromHex("0x412dd2b1") to "INSUFFICIENT_RP",
        Selector4.fromHex("0x439cc0cd") to "VERIFICATION_FAILED",
        Selector4.fromHex("0x466f52a8") to "YEAR_FIELD_NOT_FOUND_IN_PROOF",
        Selector4.fromHex("0x47bfece5") to "USDC_TRANSFER_FAILED_WITH_ERROR_MESSAGE",
        Selector4.fromHex("0x48183836") to "ZK_PASSPORT_MIN_AGE_TOO_HIGH",
        Selector4.fromHex("0x487add97") to "NEW_PAYMENT_CHANNEL_SHOULD_BE_ACTIVE",
        Selector4.fromHex("0x49de1789") to "MONTHLY_VOLUME_LIMIT_EXCEEDED",
        Selector4.fromHex("0x4b29cf0a") to "BUY_AMOUNT_EXCEEDS_USDC_LIMIT",
        Selector4.fromHex("0x4bbac5de") to "EXCHANGE_NOT_OPERATIONAL",
        Selector4.fromHex("0x4d460588") to "USER_ID_FIELD_NOT_FOUND_IN_PROOF",
        Selector4.fromHex("0x552ff5ec") to "PAYMENT_CHANNEL_NOT_FOUND",
        Selector4.fromHex("0x584a7938") to "NOT_WHITELISTED",
        Selector4.fromHex("0x58db8ed6") to "ORDER_NOT_PLACED_TO_BE_ACCEPTED",
        Selector4.fromHex("0x5d04ff4c") to "NOT_ENOUGH_ELIGIBLE_MERCHANTS",
        Selector4.fromHex("0x5eadc4c2") to "ZK_PASSPORT_SCOPE_EMPTY",
        Selector4.fromHex("0x5f765689") to "MERCHANT_ALREADY_BLACKLISTED",
        Selector4.fromHex("0x6131d13d") to "TRANSACTION_ID_DOES_NOT_MATCH",
        Selector4.fromHex("0x626b7c00") to "REWARD_ALREADY_CLAIMED",
        Selector4.fromHex("0x64301cb8") to "SELL_ORDER_AMOUNT_LIMIT_EXCEEDED",
        Selector4.fromHex("0x6500fe81") to "MONTHLY_CLAIM_LIMIT_REACHED",
        Selector4.fromHex("0x65f577de") to "ZK_VERIFICATION_REQUIRED",
        Selector4.fromHex("0x668ca75d") to "INVALID_MANAGER_DETAILS",
        Selector4.fromHex("0x675dbc86") to "MONTHLY_BUY_ORDER_COUNT_LIMIT_EXCEEDED",
        Selector4.fromHex("0x6764f4d6") to "PAYMENT_CHANNEL_NOT_APPROVED",
        Selector4.fromHex("0x688c176f") to "INVALID_ORDER_TYPE",
        Selector4.fromHex("0x69470b13") to "USERNAME_ALREADY_VERIFIED",
        Selector4.fromHex("0x69f5bfe7") to "ZK_PASSPORT_UNEXPECTED_SENDER",
        Selector4.fromHex("0x6b1b90b4") to "ORDER_NOT_PLACED_TO_BE_ACCEPTED",
        Selector4.fromHex("0x70d753bd") to "MERCHANT_NOT_FULFILLED_ELIGIBILITY_THRESHOLD",
        Selector4.fromHex("0x7290a612") to "MERCHANT_IS_NOT_APPROVED",
        Selector4.fromHex("0x73380d99") to "NO_REWARDS_TO_CLAIM",
        Selector4.fromHex("0x74785d0f") to "CANNOT_VOTE_YOURSELF",
        Selector4.fromHex("0x7642fe15") to "PASSPORT_ALREADY_VERIFIED",
        Selector4.fromHex("0x7a551e38") to "CAMPAIGN_NOT_ACTIVE",
        Selector4.fromHex("0x7aabdfe3") to "ALREADY_REFERRED",
        Selector4.fromHex("0x7bfa4b9f") to "NOT_ADMIN",
        Selector4.fromHex("0x7c9a1cf9") to "ALREADY_VOTED",
        Selector4.fromHex("0x7e2ee654") to "DAILY_VOLUME_LIMIT_EXCEEDED",
        Selector4.fromHex("0x7f61b868") to "PAYMENT_ADDRESS_ALREADY_SENT",
        Selector4.fromHex("0x7ff47425") to "NO_PENDING_MIGRATION_REQUEST",
        Selector4.fromHex("0x81c2b982") to "NO_FIAT_LIQUIDITY_ON_EXCHANGE_TO_COMPLETE_ORDER",
        Selector4.fromHex("0x83463f4a") to "SELF_REFERRAL_NOT_ALLOWED",
        Selector4.fromHex("0x8390b2dd") to "USERNAME_FIELD_NOT_FOUND_IN_PROOF",
        Selector4.fromHex("0x866e9f89") to "DISPUTE_ALREADY_SETTLED",
        Selector4.fromHex("0x8713aaba") to "MERCHANT_ALREADY_REJECTED",
        Selector4.fromHex("0x88d039ce") to "DISPUTE_NOT_RAISED",
        Selector4.fromHex("0x88ddec46") to "MIGRATION_ALREADY_REQUESTED",
        Selector4.fromHex("0x8ec051b8") to "ACCOUNT_NUMBER_DOES_NOT_MATCH",
        Selector4.fromHex("0x902ade67") to "ONLY_NEW_USERS_ALLOWED",
        Selector4.fromHex("0x917c7aef") to "DAILY_BUY_ORDER_PLACEMENT_LIMIT_EXCEEDED",
        Selector4.fromHex("0x91da284f") to "BUY_ORDER_AMOUNT_EXCEEDS_LIMIT",
        Selector4.fromHex("0x92aa7d0f") to "INVALID_MIGRATION_STATUS",
        Selector4.fromHex("0x99c8ef4d") to "INVALID_PAYMENT_CHANNEL_ID",
        Selector4.fromHex("0x9ae55bc7") to "MERCHANT_BLACKLISTED",
        Selector4.fromHex("0x9f11a53f") to "TOKEN_EMPTY",
        Selector4.fromHex("0xa1610e37") to "MANAGER_INACTIVE",
        Selector4.fromHex("0xa18ea4e8") to "USER_ID_ALREADY_VERIFIED",
        Selector4.fromHex("0xa24a13a6") to "ARRAY_LENGTH_MISMATCH",
        Selector4.fromHex("0xa6af7ebe") to "MERCHANT_IS_NOT_REGISTERED",
        Selector4.fromHex("0xa9de99ae") to "UNSTAKE_REQUEST_IS_ALREADY_PENDING",
        Selector4.fromHex("0xaa60ec26") to "INVALID_ORDER_PAYMENT_ADDRESS",
        Selector4.fromHex("0xb1198199") to "NEW_PAYMENT_CHANNEL_NOT_FOUND",
        Selector4.fromHex("0xb14a1ff3") to "USER_YEARLY_VOLUME_LIMIT_EXCEEDED",
        Selector4.fromHex("0xb28c3e29") to "DISPUTE_CAN_ONLY_BE_RAISED_AFTER_T_HOURS_OF_ORDER_PLACEMENT",
        Selector4.fromHex("0xb407b9ec") to "SELL_ORDER_AMOUNT_EXCEEDS_LIMIT",
        Selector4.fromHex("0xb87078f9") to "ZK_PASSPORT_DOMAIN_EMPTY",
        Selector4.fromHex("0xbb1cb70b") to "BATCH_TOO_LARGE",
        Selector4.fromHex("0xbba2edf9") to "SELL_AMOUNT_EXCEEDS_FIAT_LIMIT",
        Selector4.fromHex("0xc1654697") to "PAYMENT_ADDRESS_ALREADY_SENT",
        Selector4.fromHex("0xc23cefef") to "USER_IS_BLACKLISTED",
        Selector4.fromHex("0xc26d5f75") to "VOTES_PER_EPOCH_EXCEEDED",
        Selector4.fromHex("0xc56873ba") to "ORDER_EXPIRED",
        Selector4.fromHex("0xc905b99a") to "OLD_AND_NEW_PAYMENT_CHANNELS_ARE_THE_SAME",
        Selector4.fromHex("0xc991cbb1") to "TOKEN_ALREADY_EXISTS",
        Selector4.fromHex("0xcacf989a") to "NO_STAKE",
        Selector4.fromHex("0xcbdb7b30") to "TOKEN_NOT_FOUND",
        Selector4.fromHex("0xcedb41f1") to "OLD_PAYMENT_CHANNEL_SHOULD_BE_INACTIVE",
        Selector4.fromHex("0xd06ff88e") to "INSUFFICIENT_STAKED_AMOUNT",
        Selector4.fromHex("0xd13a7934") to "ZK_PASSPORT_INVALID_SCOPE",
        Selector4.fromHex("0xd2e1e6e0") to "CANNOT_PLACE_BUY_ORDERS_WITH_0_RP",
        Selector4.fromHex("0xd92e233d") to "ZERO_ADDRESS",
        Selector4.fromHex("0xe595a7bf") to "DAILY_BUY_ORDER_COUNT_LIMIT_EXCEEDED",
        Selector4.fromHex("0xe665491f") to "UNSTAKE_AMOUNT_EXCEEDED",
        Selector4.fromHex("0xe6c4247b") to "INVALID_ADDRESS",
        Selector4.fromHex("0xea8e4eb5") to "NOT_AUTHORIZED",
        Selector4.fromHex("0xebb6f34b") to "USER_IS_BLACKLISTED",
        Selector4.fromHex("0xef053cf4") to "LINKEDIN_ONLY_SUPPORTS_RP_UPDATES",
        Selector4.fromHex("0xf42e41a1") to "ORDER_AMOUNT_EXCEEDS_LIMIT",
        Selector4.fromHex("0xf4a1e014") to "MERCHANT_ALREADY_REGISTERED",
        Selector4.fromHex("0xf8bfad32") to "NOT_A_PAID_BUY_ORDER",
        Selector4.fromHex("0xfccd93cf") to "PAYMENT_CHANNEL_NOT_ACTIVE",
        Selector4.fromHex("0xfd8d4a6d") to "ZK_PASSPORT_VERIFIER_NOT_SET",
        Selector4.fromHex("0xff4f83ca") to "OLD_PAYMENT_CHANNEL_NOT_FOUND",
    )

    /** Returns the SDK error name for [selector], or null if unrecognised. */
    fun nameFor(selector: Selector4?): String? = selector?.let { SELECTOR_TO_NAME[it] }

    /** Total count of mapped selectors. Exposed for monotonic-growth tests. */
    val size: Int get() = SELECTOR_TO_NAME.size
}
